version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      APP_NAME: Felix

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:5173"
